import { Roboto } from "next/font/google";

import "./globals.css";
import Header from "./_components/Header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}   antialiased`}>
        <div className="md:px-20  shadow-sm">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
